# Generated by Django 4.0.5 on 2023-02-15 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0002_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='price',
            field=models.FloatField(),
        ),
    ]
