# Generated by Django 4.0.5 on 2023-03-24 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudapp', '0003_alter_productdetails_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productdetails',
            name='description',
            field=models.CharField(max_length=255),
        ),
    ]
